### ISSUE TITLE
Question: Data Types

### ISSUE THREAD

**Issue by TuumIO** [cmaglie/FlashStorage#9]
Hi, does this library work with all Data Types? I tried with "String" and "char" and didn't work.

Thanks

**Comment by fabltd** [comment]
Any up date on this. I tried a string but only part of it is stored.

**Comment by cmaglie** [comment]
Using just `String` won't work because you need to know the storage size upfront (while the string can grow dynamically as you add to the string itself).

To store a string you must use the method string.toCharArray(....) to copy the string content into a char array. See: https://github.com/cmaglie/FlashStorage/blob/master/examples/StoreNameAndSurname/StoreNameAndSurname.ino for a complete example.
